name: model-stroke
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Preprocess data
        run: |
          pip install -r requirements.txt
          python preprocessing.py
      - name: Train model
        run: |
          # Your ML workflow goes here
          python train.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Model Metrics" > report.md
          cat metrics.txt >> report.md
          cml publish feature_importance.jpg --md --title "Feature Importance" >> report.md
          cml publish confusion_metrics.jpg --md --title "Confusion Metrics" >> report.md
          cml send-comment report.md
